export const englishVehicleTypes = [
  { value: "heavytruck", label: "Heavy Truck" },
  { value: "lighttruck", label: "Light Truck" },
  { value: "bus", label: "Bus" },
  { value: "car", label: "Car" },
  { value: "van", label: "Van"},
];
// export const hindiVehicleTypes = [
//   { value: "hiheavytruck", label: "भारी ट्रक" },
//   { value: "hilighttruck", label: "हल्का ट्रक" },
//   { value: "hibus", label: "बस" },
//   { value: "hicar", label: "कार" },
//   { value: "hivan", label: "वैन"},
// ];
// export const malayalamVehicleTypes = [
//   { value: "maheavytruck", label: "ഭാരമേറിയ ട്രക്ക്" },
//   { value: "malighttruck", label: "ലഘു ട്രക്ക്" },
//   { value: "mabus", label: "ബസ്" },
//   { value: "macar", label: "കാർ" },
//   { value: "mavan", label: ""},
// ];


export const user = {
  name:process.env.REACT_APP_USERNAME,
  pass:process.env.REACT_APP_PASSWORD,
}  

export const startingLocations = [
  { value: "fujairah", label: "Fujairah Showroom / Workshop" },
  { value: "sharjah", label: "Sharjah Showroom / Workshop"},
  { value: "bodyshop", label: "Body shop" },
  { value: "alquoz", label: "Al Quoz Showroom / Workshop"},
  { value: "rashidiya", label: "Rashidiya Showroom / Workshop"},
]
export const endLocations = [
  { value: "abudhabi", label: "Abudhabi"},
  { value: "alain", label: "Al Ain"},
  { value: "dhafra", label: "Al Dhafra"},
  { value: "sharjah", label: "Sharjah"},
  { value: "khorfakkan", label: "Khorfakkan"},
  { value: "kalba", label: "Kalba"},
  { value: "ajman", label: "Ajman"},
  { value: "rak", label: " Ras Al Khaimah"},
  { value: "fujairah", label: "Fujairah"},
  { value: "uaq", label: "Umm Al Quwain"},
  { value: "eastern", label: "Eastern Dubai - Deira & Dubai"},
  { value: "central", label: "Central Dubai - AL Quoz &  Barsha"},
  { value: "western", label: "Workshop Dubai - Jebal Ali"},
  { value: "hatta", label: "Hatta"}
]

export const dataset = [
  {start: "fujairah", end: "abudhabi", truckType: "Standard Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:750, carsPrice:null},
  {start: "fujairah", end: "alain", truckType: "Standard Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:530, carsPrice:null},
  {start: "fujairah", end: "dhafra", truckType: "Standard Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:1290, carsPrice:null},
  {start: "fujairah", end: "sharjah", truckType: "Standard Truck Required", amctPrice:300, aaaPrice:350, emiratesPrice:320, carsPrice:null},
  {start: "fujairah", end: "khorfakkan", truckType: "Standard Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:90, carsPrice:null},
  {start: "fujairah", end: "kalba", truckType: "Standard Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:90, carsPrice:null},
  {start: "fujairah", end: "ajman", truckType: "Standard Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:350, carsPrice:null},
  {start: "fujairah", end: "rak", truckType: "Standard Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:330, carsPrice:null},
  {start: "fujairah", end: "fujairah", truckType: "Standard Truck Required", amctPrice:null , aaaPrice:null, emiratesPrice:90, carsPrice:null},
  {start: "fujairah", end: "uaq", truckType: "Standard Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:380, carsPrice:null},
  {start: "fujairah", end: "eastern", truckType: "Standard Truck Required", amctPrice:350 , aaaPrice:400, emiratesPrice:390, carsPrice:null},
  {start: "fujairah", end: "central", truckType: "Standard Truck Required", amctPrice:350 , aaaPrice:400, emiratesPrice:440, carsPrice:null},
  {start: "fujairah", end: "western", truckType: "Standard Truck Required", amctPrice:400 , aaaPrice:550, emiratesPrice:470, carsPrice:null},
  {start: "fujairah", end: "hatta", truckType: "Standard Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:200, carsPrice:null},
  // ------------------------------
  {start: "sharjah", end: "abudhabi", truckType: "Standard Truck Required", amctPrice:400, aaaPrice:450, emiratesPrice:480, carsPrice:null },
  {start: "sharjah", end: "alain", truckType: "Standard Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:470, carsPrice:null },
  {start: "sharjah", end: "dhafra", truckType: "Standard Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:1020, carsPrice:null },
  {start: "sharjah", end: "sharjah", truckType: "Standard Truck Required", amctPrice:110, aaaPrice:125, emiratesPrice:90, carsPrice:null },
  {start: "sharjah", end: "khorfakkan", truckType: "Standard Truck Required", amctPrice:350, aaaPrice:350, emiratesPrice:320, carsPrice:null },
  {start: "sharjah", end: "kalba", truckType: "Standard Truck Required", amctPrice:350, aaaPrice:null, emiratesPrice:320, carsPrice:null},
  {start: "sharjah", end: "ajman", truckType: "Standard Truck Required", amctPrice:120, aaaPrice:175, emiratesPrice:90, carsPrice:null},
  {start: "sharjah", end: "rak", truckType: "Standard Truck Required", amctPrice:300, aaaPrice:325, emiratesPrice:230, carsPrice:null},
  {start: "sharjah", end: "fujairah", truckType: "Standard Truck Required", amctPrice:300, aaaPrice:350, emiratesPrice:320, carsPrice:null},
  {start: "sharjah", end: "uaq", truckType: "Standard Truck Required", amctPrice:175, aaaPrice:250, emiratesPrice:110, carsPrice:null},
  {start: "sharjah", end: "eastern", truckType: "Standard Truck Required", amctPrice:125 , aaaPrice:150, emiratesPrice:120, carsPrice:null },
  {start: "sharjah", end: "central", truckType: "Standard Truck Required", amctPrice:125, aaaPrice:150, emiratesPrice:170, carsPrice:null},
  {start: "sharjah", end: "western", truckType: "Standard Truck Required", amctPrice:250, aaaPrice:350, emiratesPrice:210, carsPrice:null},
  {start: "sharjah", end: "hatta", truckType: "Standard Truck Required", amctPrice:225, aaaPrice:540, emiratesPrice:360, carsPrice:null},
  // ------------------------------
  {start: "bodyshop", end: "abudhabi", truckType: "Standard Truck Required", amctPrice:300, aaaPrice:350, emiratesPrice:320, carsPrice:null},
  {start: "bodyshop", end: "alain", truckType: "Standard Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:450, carsPrice:null},
  {start: "bodyshop", end: "dhafra", truckType: "Standard Truck Required", amctPrice:null , aaaPrice:null, emiratesPrice:840, carsPrice:null},
  {start: "bodyshop", end: "sharjah", truckType: "Standard Truck Required", amctPrice:250, aaaPrice:350, emiratesPrice:210, carsPrice:null},
  {start: "bodyshop", end: "khorfakkan", truckType: "Standard Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:470, carsPrice:null},
  {start: "bodyshop", end: "kalba", truckType: "Standard Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:470, carsPrice:null},
  {start: "bodyshop", end: "ajman", truckType: "Standard Truck Required", amctPrice:300, aaaPrice:300, emiratesPrice:260, carsPrice:null},
  {start: "bodyshop", end: "rak", truckType: "Standard Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:470, carsPrice:null},
  {start: "bodyshop", end: "fujairah", truckType: "Standard Truck Required", amctPrice:400, aaaPrice:550, emiratesPrice:470, carsPrice:null},
  {start: "bodyshop", end: "uaq", truckType: "Standard Truck Required", amctPrice:350, aaaPrice:375, emiratesPrice:350, carsPrice:null},
  {start: "bodyshop", end: "eastern", truckType: "Standard Truck Required", amctPrice:175, aaaPrice:225, emiratesPrice:90, carsPrice:null},
  {start: "bodyshop", end: "central", truckType: "Standard Truck Required", amctPrice:175, aaaPrice:225, emiratesPrice:90, carsPrice:null},
  {start: "bodyshop", end: "western", truckType: "Standard Truck Required", amctPrice:110, aaaPrice:175, emiratesPrice:90, carsPrice:null},
  {start: "bodyshop", end: "hatta", truckType: "Standard Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:510, carsPrice:null},
  // ------------------------------

  {start: "alquoz", end: "abudhabi", truckType: "Standard Truck Required", amctPrice:350, aaaPrice:375, emiratesPrice:330, carsPrice:null},
  {start: "alquoz", end: "alain", truckType: "Standard Truck Required", amctPrice:350, aaaPrice:375, emiratesPrice:450, carsPrice:null},
  {start: "alquoz", end: "dhafra", truckType: "Standard Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:900, carsPrice:null},
  {start: "alquoz", end: "sharjah", truckType: "Standard Truck Required", amctPrice:125, aaaPrice:150, emiratesPrice:170, carsPrice:null},
  {start: "alquoz", end: "khorfakkan", truckType: "Standard Truck Required", amctPrice:350, aaaPrice:430, emiratesPrice:440, carsPrice:null},
  {start: "alquoz", end: "kalba", truckType: "Standard Truck Required", amctPrice:350, aaaPrice:null, emiratesPrice:440, carsPrice:null},
  {start: "alquoz", end: "ajman", truckType: "Standard Truck Required", amctPrice:150, aaaPrice:200, emiratesPrice:200, carsPrice:null},
  {start: "alquoz", end: "rak", truckType: "Standard Truck Required", amctPrice:315, aaaPrice:375, emiratesPrice:410, carsPrice:null},
  {start: "alquoz", end: "fujairah", truckType: "Standard Truck Required", amctPrice:350, aaaPrice:400, emiratesPrice:440, carsPrice:null},
  {start: "alquoz", end: "uaq", truckType: "Standard Truck Required", amctPrice:200, aaaPrice:275, emiratesPrice:270, carsPrice:null},
  {start: "alquoz", end: "eastern", truckType: "Standard Truck Required", amctPrice:110, aaaPrice:140, emiratesPrice:90, carsPrice:null},
  {start: "alquoz", end: "central", truckType: "Standard Truck Required", amctPrice:110, aaaPrice:140, emiratesPrice:90, carsPrice:null},
  {start: "alquoz", end: "western", truckType: "Standard Truck Required", amctPrice:175, aaaPrice:225, emiratesPrice:90, carsPrice:null},
  {start: "alquoz", end: "hatta", truckType: "Standard Truck Required", amctPrice:250, aaaPrice:490, emiratesPrice:470, carsPrice:null},
  // ------------------------------
  
  {start: "rashidiya", end: "abudhabi", truckType: "Standard Truck Required", amctPrice:350, aaaPrice:375, emiratesPrice:360, carsPrice:null},
  {start: "rashidiya", end: "alain", truckType: "Standard Truck Required", amctPrice:350, aaaPrice:375, emiratesPrice:440, carsPrice:null},
  {start: "rashidiya", end: "dhafra", truckType: "Standard Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:950, carsPrice:null},
  {start: "rashidiya", end: "sharjah", truckType: "Standard Truck Required", amctPrice:125, aaaPrice:150, emiratesPrice:120, carsPrice:null},
  {start: "rashidiya", end: "khorfakkan", truckType: "Standard Truck Required", amctPrice:350, aaaPrice:430, emiratesPrice:390, carsPrice:null},
  {start: "rashidiya", end: "kalba", truckType: "Standard Truck Required", amctPrice:350, aaaPrice:null, emiratesPrice:390, carsPrice:null},
  {start: "rashidiya", end: "ajman", truckType: "Standard Truck Required", amctPrice:150, aaaPrice:200, emiratesPrice:140, carsPrice:null},
  {start: "rashidiya", end: "rak", truckType: "Standard Truck Required", amctPrice:315, aaaPrice:375, emiratesPrice:330, carsPrice:null},
  {start: "rashidiya", end: "fujairah", truckType: "Standard Truck Required", amctPrice:350, aaaPrice:400, emiratesPrice:390, carsPrice:null},
  {start: "rashidiya", end: "uaq", truckType: "Standard Truck Required", amctPrice:200, aaaPrice:275, emiratesPrice:180, carsPrice:null},
  {start: "rashidiya", end: "eastern", truckType: "Standard Truck Required", amctPrice:110, aaaPrice:140, emiratesPrice:90, carsPrice:null},
  {start: "rashidiya", end: "central", truckType: "Standard Truck Required", amctPrice:110, aaaPrice:140, emiratesPrice:90, carsPrice:null},
  {start: "rashidiya", end: "western", truckType: "Standard Truck Required", amctPrice:175, aaaPrice:225, emiratesPrice:90, carsPrice:null},
  {start: "rashidiya", end: "hatta", truckType: "Standard Truck Required", amctPrice:250, aaaPrice:490, emiratesPrice:410, carsPrice:null},
  // --------------------------------------- Flat Bed Truck Required
  {start: "fujairah", end: "abudhabi", truckType: "Flat Bed Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:930, carsPrice:null},
  {start: "fujairah", end: "alain", truckType: "Flat Bed Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:650, carsPrice:null},
  {start: "fujairah", end: "dhafra", truckType: "Flat Bed Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:1590, carsPrice:null},
  {start: "fujairah", end: "sharjah", truckType: "Flat Bed Truck Required", amctPrice:300, aaaPrice:350, emiratesPrice:390, carsPrice:null},
  {start: "fujairah", end: "khorfakkan", truckType: "Flat Bed Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:110, carsPrice:null},
  {start: "fujairah", end: "kalba", truckType: "Flat Bed Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:110, carsPrice:null},
  {start: "fujairah", end: "ajman", truckType: "Flat Bed Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:430, carsPrice:null},
  {start: "fujairah", end: "rak", truckType: "Flat Bed Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:410, carsPrice:null},
  {start: "fujairah", end: "fujairah", truckType: "Flat Bed Truck Required", amctPrice:null , aaaPrice:null, emiratesPrice:110, carsPrice:null},
  {start: "fujairah", end: "uaq", truckType: "Flat Bed Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:460, carsPrice:null},
  {start: "fujairah", end: "eastern", truckType: "Flat Bed Truck Required", amctPrice:350 , aaaPrice:400, emiratesPrice:480, carsPrice:null},
  {start: "fujairah", end: "central", truckType: "Flat Bed Truck Required", amctPrice:350 , aaaPrice:400, emiratesPrice:540, carsPrice:null},
  {start: "fujairah", end: "western", truckType: "Flat Bed Truck Required", amctPrice:400 , aaaPrice:550, emiratesPrice:570, carsPrice:null},
  {start: "fujairah", end: "hatta", truckType: "Flat Bed Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:240, carsPrice:null},
  // ------------------------------
  {start: "sharjah", end: "abudhabi", truckType: "Flat Bed Truck Required", amctPrice:400, aaaPrice:450, emiratesPrice:590, carsPrice:null },
  {start: "sharjah", end: "alain", truckType: "Flat Bed Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:570, carsPrice:null },
  {start: "sharjah", end: "dhafra", truckType: "Flat Bed Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:1260, carsPrice:null },
  {start: "sharjah", end: "sharjah", truckType: "Flat Bed Truck Required", amctPrice:110, aaaPrice:125, emiratesPrice:110, carsPrice:null },
  {start: "sharjah", end: "khorfakkan", truckType: "Flat Bed Truck Required", amctPrice:350, aaaPrice:350, emiratesPrice:390, carsPrice:null },
  {start: "sharjah", end: "kalba", truckType: "Flat Bed Truck Required", amctPrice:350, aaaPrice:null, emiratesPrice:390, carsPrice:null},
  {start: "sharjah", end: "ajman", truckType: "Flat Bed Truck Required", amctPrice:120, aaaPrice:175, emiratesPrice:110, carsPrice:null},
  {start: "sharjah", end: "rak", truckType: "Flat Bed Truck Required", amctPrice:300, aaaPrice:325, emiratesPrice:280, carsPrice:null},
  {start: "sharjah", end: "fujairah", truckType: "Flat Bed Truck Required", amctPrice:300, aaaPrice:350, emiratesPrice:390, carsPrice:null},
  {start: "sharjah", end: "uaq", truckType: "Flat Bed Truck Required", amctPrice:175, aaaPrice:250, emiratesPrice:130, carsPrice:null},
  {start: "sharjah", end: "eastern", truckType: "Flat Bed Truck Required", amctPrice:125 , aaaPrice:150, emiratesPrice:150, carsPrice:null },
  {start: "sharjah", end: "central", truckType: "Flat Bed Truck Required", amctPrice:125, aaaPrice:150, emiratesPrice:200, carsPrice:null},
  {start: "sharjah", end: "western", truckType: "Flat Bed Truck Required", amctPrice:250, aaaPrice:350, emiratesPrice:260, carsPrice:null},
  {start: "sharjah", end: "hatta", truckType: "Flat Bed Truck Required", amctPrice:225, aaaPrice:540, emiratesPrice:440, carsPrice:null},
  // ------------------------------
  {start: "bodyshop", end: "abudhabi", truckType: "Flat Bed Truck Required", amctPrice:300, aaaPrice:350, emiratesPrice:390, carsPrice:null},
  {start: "bodyshop", end: "alain", truckType: "Flat Bed Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:560, carsPrice:null},
  {start: "bodyshop", end: "dhafra", truckType: "Flat Bed Truck Required", amctPrice:null , aaaPrice:null, emiratesPrice:1040, carsPrice:null},
  {start: "bodyshop", end: "sharjah", truckType: "Flat Bed Truck Required", amctPrice:250, aaaPrice:350, emiratesPrice:260, carsPrice:null},
  {start: "bodyshop", end: "khorfakkan", truckType: "Flat Bed Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:570, carsPrice:null},
  {start: "bodyshop", end: "kalba", truckType: "Flat Bed Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:570, carsPrice:null},
  {start: "bodyshop", end: "ajman", truckType: "Flat Bed Truck Required", amctPrice:300, aaaPrice:300, emiratesPrice:320, carsPrice:null},
  {start: "bodyshop", end: "rak", truckType: "Flat Bed Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:570, carsPrice:null},
  {start: "bodyshop", end: "fujairah", truckType: "Flat Bed Truck Required", amctPrice:400, aaaPrice:550, emiratesPrice:570, carsPrice:null},
  {start: "bodyshop", end: "uaq", truckType: "Flat Bed Truck Required", amctPrice:350, aaaPrice:375, emiratesPrice:430, carsPrice:null},
  {start: "bodyshop", end: "eastern", truckType: "Flat Bed Truck Required", amctPrice:175, aaaPrice:225, emiratesPrice:110, carsPrice:null},
  {start: "bodyshop", end: "central", truckType: "Flat Bed Truck Required", amctPrice:175, aaaPrice:225, emiratesPrice:110, carsPrice:null},
  {start: "bodyshop", end: "western", truckType: "Flat Bed Truck Required", amctPrice:110, aaaPrice:175, emiratesPrice:110, carsPrice:null},
  {start: "bodyshop", end: "hatta", truckType: "Flat Bed Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:630, carsPrice:null},
  // ------------------------------

  {start: "alquoz", end: "abudhabi", truckType: "Flat Bed Truck Required", amctPrice:350, aaaPrice:375, emiratesPrice:410, carsPrice:null},
  {start: "alquoz", end: "alain", truckType: "Flat Bed Truck Required", amctPrice:350, aaaPrice:375, emiratesPrice:560, carsPrice:null},
  {start: "alquoz", end: "dhafra", truckType: "Flat Bed Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:1110, carsPrice:null},
  {start: "alquoz", end: "sharjah", truckType: "Flat Bed Truck Required", amctPrice:125, aaaPrice:150, emiratesPrice:200, carsPrice:null},
  {start: "alquoz", end: "khorfakkan", truckType: "Flat Bed Truck Required", amctPrice:350, aaaPrice:430, emiratesPrice:540, carsPrice:null},
  {start: "alquoz", end: "kalba", truckType: "Flat Bed Truck Required", amctPrice:350, aaaPrice:null, emiratesPrice:540, carsPrice:null},
  {start: "alquoz", end: "ajman", truckType: "Flat Bed Truck Required", amctPrice:150, aaaPrice:200, emiratesPrice:240, carsPrice:null},
  {start: "alquoz", end: "rak", truckType: "Flat Bed Truck Required", amctPrice:315, aaaPrice:375, emiratesPrice:500, carsPrice:null},
  {start: "alquoz", end: "fujairah", truckType: "Flat Bed Truck Required", amctPrice:350, aaaPrice:400, emiratesPrice:540, carsPrice:null},
  {start: "alquoz", end: "uaq", truckType: "Flat Bed Truck Required", amctPrice:200, aaaPrice:275, emiratesPrice:330, carsPrice:null},
  {start: "alquoz", end: "eastern", truckType: "Flat Bed Truck Required", amctPrice:110, aaaPrice:140, emiratesPrice:110, carsPrice:null},
  {start: "alquoz", end: "central", truckType: "Flat Bed Truck Required", amctPrice:110, aaaPrice:140, emiratesPrice:110, carsPrice:null},
  {start: "alquoz", end: "western", truckType: "Flat Bed Truck Required", amctPrice:175, aaaPrice:225, emiratesPrice:110, carsPrice:null},
  {start: "alquoz", end: "hatta", truckType: "Flat Bed Truck Required", amctPrice:250, aaaPrice:490, emiratesPrice:570, carsPrice:null},
  // ------------------------------
  
  {start: "rashidiya", end: "abudhabi", truckType: "Flat Bed Truck Required", amctPrice:350, aaaPrice:375, emiratesPrice:440, carsPrice:null},
  {start: "rashidiya", end: "alain", truckType: "Flat Bed Truck Required", amctPrice:350, aaaPrice:375, emiratesPrice:540, carsPrice:null},
  {start: "rashidiya", end: "dhafra", truckType: "Flat Bed Truck Required", amctPrice:null, aaaPrice:null, emiratesPrice:1170, carsPrice:null},
  {start: "rashidiya", end: "sharjah", truckType: "Flat Bed Truck Required", amctPrice:125, aaaPrice:150, emiratesPrice:150, carsPrice:null},
  {start: "rashidiya", end: "khorfakkan", truckType: "Flat Bed Truck Required", amctPrice:350, aaaPrice:430, emiratesPrice:480, carsPrice:null},
  {start: "rashidiya", end: "kalba", truckType: "Flat Bed Truck Required", amctPrice:350, aaaPrice:null, emiratesPrice:480, carsPrice:null},
  {start: "rashidiya", end: "ajman", truckType: "Flat Bed Truck Required", amctPrice:150, aaaPrice:200, emiratesPrice:170, carsPrice:null},
  {start: "rashidiya", end: "rak", truckType: "Flat Bed Truck Required", amctPrice:315, aaaPrice:375, emiratesPrice:410, carsPrice:null},
  {start: "rashidiya", end: "fujairah", truckType: "Flat Bed Truck Required", amctPrice:350, aaaPrice:400, emiratesPrice:480, carsPrice:null},
  {start: "rashidiya", end: "uaq", truckType: "Flat Bed Truck Required", amctPrice:200, aaaPrice:275, emiratesPrice:220, carsPrice:null},
  {start: "rashidiya", end: "eastern", truckType: "Flat Bed Truck Required", amctPrice:110, aaaPrice:140, emiratesPrice:110, carsPrice:null},
  {start: "rashidiya", end: "central", truckType: "Flat Bed Truck Required", amctPrice:110, aaaPrice:140, emiratesPrice:110, carsPrice:null},
  {start: "rashidiya", end: "western", truckType: "Flat Bed Truck Required", amctPrice:175, aaaPrice:225, emiratesPrice:110, carsPrice:null},
  {start: "rashidiya", end: "hatta", truckType: "Flat Bed Truck Required", amctPrice:250, aaaPrice:490, emiratesPrice:500, carsPrice:null},

];
export const basha = [
  {value:'en', name:'English'},
  {value:'ma', name:'മലയാളം '},
  {value:'hi', name:'हिन्दी'},
]

export const language = {
  hi:{
    home:"होम",
    people:"लोग",
    fleet:"फ़्लीट",
    trip:"ट्रिप",
    signout:"साइन आउट",
    dashboard:"डैशबोर्ड",
    employees:"कर्मचारी",
    passportExpiry:"पासपोर्ट की समाप्ति",
    visaExpiry:"वीज़ा समाप्ति",
    ohcExpiry:"ओएचसी समाप्ति",
    odpExpiry:"ओडीसी समाप्ति",
    fireSafetyExpiry:"अग्नि एवं सुरक्षा समाप्ति",
    portPassExpiry:"पोर्ट पास की समाप्ति",
    registrationExpiry:" पंजीकरण समाप्ति",
    insuranceExpiry:"बीमा समाप्ति",
    advertisementExpiry:"विज्ञापन समाप्ति",
    isoExpiry:"आईएसओ प्रमाणन समाप्ति",
    firstName:"प्रथम नाम",
    middleName:"मध्य नाम",
    lastName:"उपनाम",
    employeeId:"कर्मचारी आईडी",
    employeeRegistration:"कर्मचारी पंजीकरण",
    save:"सहेजें",
    close:"बंद करें",
    employeeList:"कर्मचारी सूची",
    searchEmployee:"नाम से खोजें..",
    successMessage:"विवरण सफलतापूर्वक सहेजा गया...",
    fleetRegistration:"बेड़े पंजीकरण",
    plateNo:"प्लेट नंबर",
    chassisNo:"चेसिस नंबर",
    vehicleType:"वाहन प्रकार",
    manufacturer:"निर्माता",
    spareKey:"अतिरिक्त चाबी",
    placeholderFleet:"कोई भी वाहन प्रकार चुनें...",
    register:"रजिस्टर",
    fleetList:"बेड़े की सूची",
    priceComparison:"मूल्य तुलना",
    update:"अद्यतन",
    delete:"हटाना",
    placeHolderFleetList:"प्लेट नंबर से खोजें...",
    selectBrand:"कोई भी ब्रांड चुनें",
    selectType:"ब्रांड से कोई भी कार मॉडल चुनें",
    supplierPriceComparison:"आपूर्तिकर्ता मूल्य तुलना",
    startPoint:"यात्रा प्रारंभिक स्थान",
    endPoint:"यात्रा अंतिम बिंदु",
  },
  en:{
    home:"Home",
    people:"People",
    fleet:"Fleet",
    trip:"Trip",
    signout:"Sign Out",
    dashboard:"Dashboard",
    employees:"Employees",
    passportExpiry:"Passport Expiry",
    visaExpiry:"Visa Expiry",
    ohcExpiry:"OHC Expiry",
    odpExpiry:"ODP Expiry",
    fireSafetyExpiry:"Fire & Safety Expiry",
    portPassExpiry:"Port Pass Expiry",
    registrationExpiry:"Registration Expiry",
    insuranceExpiry:"Insurance Expiry",
    advertisementExpiry:"Advertisement Expiry",
    isoExpiry:"ISO Expiry",
    firstName:"First Name",
    middleName:"Middle Name",
    lastName:"Last Name",
    employeeId:"EmployeeId",
    employeeRegistration:"Employee Registration",
    save:"Save",
    close:"Close",
    employeeList:"Employee List",
    searchEmployee:"Search by name...",
    successMessage:"Data saved successfully...",
    fleetRegistration:"Fleet Registration",
    plateNo:"Plate No",
    chassisNo:"Chassis No",
    vehicleType:"Vehicle Type",
    manufacturer:"Manufacturer",
    spareKey:"Spare Key",
    placeholderFleet:"Select any vehicle type...",
    register:"Register",
    fleetList:"Fleet List",
    priceComparison:"Price Comparison",
    update:"Update",
    delete:"Delete",
    placeHolderFleetList:"Search by Plate number...",
    selectBrand:"Select any brand",
    selectType:"Select any car model from the brand",
    supplierPriceComparison:"Supplier Price Comparison",
    startPoint:"Trip starting point",
    endPoint:"Trip end point",
  },
  ma:{
    home:"മുഖ്യപേജ്",
    people:"പീപ്പിൾ ",
    fleet:"ഫ്ലീറ്റ്",
    trip:"ട്രിപ്പ്",
    signout:"സൈൻ ഔട്ട്",
    dashboard:"ഡാഷ്ബോർഡ്",
    employees:"ജീവനക്കാർ",
    passportExpiry:"പാസ്പോർട്ട് കാലാവധി",
    visaExpiry:"വിസ കാലാവധി",
    ohcExpiry:"OHC കാലാവധി",
    odpExpiry:"ODP കാലാവധി",
    fireSafetyExpiry:"ഫയർ & സേഫ്റ്റി കാലാവധി",
    portPassExpiry:"പോർട്ട് പാസ് കാലാവധി",
    registrationExpiry:"രജിസ്ട്രേഷൻ കാലാവധി",
    insuranceExpiry:"ഇൻഷുറൻസ് കാലാവധി",
    advertisementExpiry:"പരസ്യ കാലാവധി",
    isoExpiry:"ISO സർട്ടിഫിക്കറ്റ് കാലാവധി",
    firstName:"ആദ്യ പേര്",
    middleName:"മധ്യ പേര്",
    lastName:"കുടുംബനാമം",
    employeeId:"ജീവനക്കാരന്റെ ഐഡി",
    employeeRegistration:"ജീവനക്കാരുടെ രജിസ്ട്രേഷൻ",
    save:"സംരക്ഷിക്കുക",
    close:"അടയ്ക്കുക",
    employeeList:"ജീവനക്കാരുടെ ലിസ്റ്റ്",
    searchEmployee:"പേരുപ്രകാരം തിരയുക...",
    successMessage:"വിശദാംശങ്ങൾ വിജയകരമായി സംരക്ഷിച്ചു...",
    fleetRegistration:"ഫ്ലീറ്റ് രജിസ്ട്രേഷൻ",
    plateNo:"പ്ലേറ്റ് നമ്പർ",
    chassisNo:"ചാസിസ് നമ്പർ",
    vehicleType:"വാഹനം തരം",
    manufacturer:"നിർമ്മാതാവ്",
    spareKey:"അധിക കീ",
    placeholderFleet:"ഏതെങ്കിലും വാഹന തരം തിരഞ്ഞെടുക്കുക...",
    register:"രജിസ്റ്റർ",
    fleetList:"വാഹനങ്ങളുടെ പട്ടിക",
    priceComparison:'വില താരതമ്യം',
    update:"അപ്ഡേറ്റ്",
    delete:"ഡിലീറ്റ്",
    placeHolderFleetList:"പ്ലേറ്റ് നമ്പർ പ്രകാരം തിരയുക...",
    selectBrand:"ഏത് ബ്രാന്റും തിരഞ്ഞെടുക്കുക",
    selectType:"ബ്രാൻഡിൽ നിന്ന് ഏതെങ്കിലും കാ‍ർ മോഡൽ തിരഞ്ഞെടുക്കുക",
    supplierPriceComparison:"വിതരണക്കാരുടെ വില താരതമ്യം",
    startPoint:"യാത്ര ആരംഭ ബിന്ദു",
    endPoint:"യാത്ര അവസാന ബിന്ദു",
  }
};

  









